apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  namespace: test-dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data  # Directory on the host node
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany