apiVersion: v1
kind: Pod
metadata:
  namespace: test-dev
  name: kafka-3
  labels:
    app: "Brokers"
spec:
  containers:
    - name: broker
      image: sachin456/kafkaserver:v2
      env:
        - name: "ID"
          value: "2"
        - name: PORT
          value: "9093"
        - name: LOG_DIR
          value: "/usr/logs"
        - name: ZOOKEEPER_IP
          value: "zookeeper-service.test-dev.svc.cluster.local"
        - name: zPORT
          value: "2181"
        - name: LISTENER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      ports:
        - containerPort: 9093
          name: broker-port