apiVersion: v1
kind: Pod
metadata:
  namespace: test-dev
  name: zookeeper-0
  labels:
    app: "Zookeepers"
spec:
  containers:
    - name: test2
      image: sachin456/zookeeper:test
      env:
        - name: "ZOO_CLIENT_PORT"
          value: "2181"
      ports:
      - containerPort: 2181
        name: zoo-port